const siteData = {
    restaurants: [
        {
            id: "tandoori-hut",
            name: "Tandoori Hut",
            description: "Authentic North Indian cuisine with traditional tandoor-cooked dishes and aromatic curries.",
            image: "../assets/images/tandoori-hut.jpg",
            category: "desi indian vegetarian",
            rating: 4.8,
            price: "$$",
            location: "3171 Main St, Buffalo, NY 14214",
            badges: ["Desi", "Indian"],
            url: "https://www.tandoorihutbuffalo.com",
            featured: true
        },
        {
            id: "buffalo-tikka-house",
            name: "Buffalo Tikka House",
            description: "Famous for its authentic Pakistani street food, sizzlers, and traditional Lahori flavors.",
            image: "https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=800",
            category: "desi pakistani",
            rating: 4.7,
            price: "$$",
            location: "948 Main St, Buffalo, NY 14202",
            badges: ["Desi", "Pakistani"],
            url: "https://buffalotikkahouse.co",
            featured: true
        },
        {
            id: "spices-of-india",
            name: "Spices of India",
            description: "Exquisite Bangladeshi and Bengali cuisine featuring traditional fish curries and biryanis.",
            image: "https://images.unsplash.com/photo-1567337710282-00832b415979?w=800",
            category: "desi bangladeshi",
            rating: 4.6,
            price: "$",
            location: "Bailey Ave, Buffalo, NY 14215",
            badges: ["Desi", "Bangladeshi"],
            url: "https://spicesofindiawny.com",
            featured: true
        },
        {
            id: "pinos-pizza",
            name: "Pino's Pizza",
            description: "Classic Italian-American pizzeria serving thick-crust pies, wings, and hot subs.",
            image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800",
            category: "italian american",
            rating: 4.5,
            price: "$",
            location: "123 Terrace, Buffalo, NY 14202",
            badges: ["Italian", "Pizza"],
            url: "https://www.pinospizza.com"
        },
        {
            id: "augies",
            name: "Augie's",
            description: "Gourmet burgers and handcrafted shakes in a relaxed, industrial-chic setting.",
            image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=800",
            category: "american",
            rating: 4.7,
            price: "$$",
            location: "346 Connecticut St, Buffalo, NY 14213",
            badges: ["American", "Burgers"],
            url: "https://www.getaugies.com"
        },
        {
            id: "rinthai",
            name: "Rin Thai Bistro",
            description: "Traditional Thai dishes including Pad Thai, Green Curry, and spicy basil stir-fries.",
            image: "../assets/images/r-pad-thai.jpg",
            category: "asian",
            rating: 4.8,
            price: "$$",
            location: "4446 Main St, Buffalo, NY 14226",
            badges: ["Asian", "Thai"],
            url: "https://www.rinthaibistro.com"
        },
        {
            id: "la-galera",
            name: "La Galera Mexican",
            description: "Vibrant Mexican eatery offering tacos, enchiladas, and house-made margaritas.",
            image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800",
            category: "mexican",
            rating: 4.6,
            price: "$$",
            location: "101 Niagara St, Buffalo, NY 14201",
            badges: ["Mexican", "Tacos"],
            url: "https://www.lagaleramexican.com"
        },
        {
            id: "sunshine-vegan-eats",
            name: "Sunshine Vegan Eats",
            description: "Fully plant-based menu featuring creative vegan breakfast, burgers, appetizers, and fresh juices.",
            image: "../assets/images/r-sun-eats.webp",
            category: "vegetarian asian",
            rating: 4.9,
            price: "$$",
            location: "893 Jefferson Ave, Buffalo, NY 14204",
            badges: ["Vegetarian", "Vegan"],
            url: "https://www.sunshineveganeats.com"
        },
        {
            "id": "strong-hearts-716",
            "name": "Strong Buffalo",
            "description": "Vegan comfort food eatery serving 100% plant-based burgers, sandwiches, vegan wings, loaded fries, milkshakes, and more in a casual setting.",
            "image": "../assets/images/r-vegan-1.jpg",
            "category": "vegetarian american",
            "rating": null,
            "price": "$$",
            "location": "295 Niagara St, Buffalo, NY 14201",
            "badges": ["Vegan"],
            "url": "https://www.stronghearts716.com"
        },
        {
            "id": "wind-buffalo",
            "name": "Wind Japanese & Thai",
            "description": "All-you-can-eat Japanese and Thai restaurant featuring sushi, sashimi, hibachi, wok dishes, and a la carte options in a lively setting.",
            "image": "../assets/images/r-thai-1.jpg",
            "category": "asian",
            "rating": null,
            "price": "$$",
            "location": "7566 Transit Rd, Buffalo, NY 14221",
            "badges": ["Japanese", "Thai"],
            "url": "https://www.windbuffalo.com/?utm_source=google&utm_medium=wix_google_business_profile&utm_campaign=7909774084127326056"
        },
        {
            "id": "la-fiesta-cantina",
            "name": "La Fiesta Cantina",
            "description": "Mexican restaurant serving classic fare like tacos, burritos, fajitas, margaritas, and shareable appetizers with a festive atmosphere.",
            "image": "../assets/images/r-mexican-2.jpg",
            "category": "mexican",
            "rating": null,
            "price": "$$",
            "location": "73 Allen St, Buffalo, NY 14202",
            "badges": ["Mexican"],
            "url": "https://lafiestabuffalo.com"
        },
        {
            "id": "aguacates-mexican-bar-grill",
            "name": "Aguacates Mexican Bar & Grill",
            "description": "Authentic Mexican cuisine with a wide variety of dishes including fajitas, burritos, tacos, salads, and combos, plus catering services.",
            "image": "../assets/images/r-mexican-1.jpg",
            "category": "mexican",
            "rating": null,
            "price": "$$",
            "location": "765 Elmwood Ave, Buffalo, NY 14222",
            "badges": ["Mexican"],
            "url": "https://aguacatesbuffalo.com"
        }

    ],
    events: [
        {
            id: "yoga-park",
            name: "Yoga in the Park",
            description: "Join us for a rejuvenating outdoor yoga session suitable for all levels.",
            image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=1200",
            category: "fitness health wellness",
            badges: ["Fitness", "Wellness"],
            date: "Jan 25, 2026",
            time: "09:00 AM",
            location: "Delaware Park, Buffalo, NY",
            price: "Free",
            featured: false,
            month: "Jan",
            day: "25"
        },
        {
            id: "buffalo-music-fest",
            name: "Buffalo Music Festival 2026",
            description: "Live music featuring local and international artists across multiple genres.",
            image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1200",
            category: "music food entertainment",
            badges: ["Music", "Festival"],
            date: "Feb 3-23, 2026",
            time: "06:30 PM",
            location: "Canalside, Buffalo, NY",
            price: "$25",
            url: "https://www.musicisart.org",
            featured: true,
            month: "Feb",
            day: "3-23"
        },
        {
            id: "desi-culture-fair",
            name: "Desi Food & Culture Fair",
            description: "A vibrant celebration of South Asian food, music, dance, and traditional crafts.",
            image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=1200",
            category: "food entertainment",
            badges: ["Desi", "Food"],
            date: "March 15, 2026",
            time: "12:00 PM",
            location: "Niagara Square, Buffalo, NY",
            price: "Free",
            url: "https://allevents.in/buffalo",
            featured: true,
            month: "Mar",
            day: "15"
        },
        {
            id: "bollywood-night",
            name: "Bollywood Night",
            description: "A night of dance, music, and celebration of Bollywood culture.",
            image: "https://images.unsplash.com/photo-1514525253344-f24672a230c5?w=1200",
            category: "entertainment",
            badges: ["Desi", "Dance"],
            date: "March 22, 2026",
            time: "07:00 PM",
            location: "Buffalo Convention Center, NY",
            price: "Free",
            featured: false,
            month: "Mar",
            day: "22"
        },
        {
            id: "holi-fest",
            name: "Holi Festival of Colors",
            description: "Celebrate the arrival of spring with the traditional festival of colors.",
            image: "https://images.unsplash.com/photo-1463138541530-50d4f13426e2?w=1200",
            category: "cultural entertainment desi",
            badges: ["Cultural", "Desi", "Spring"],
            date: "April 12, 2026",
            time: "11:00 AM",
            location: "Outer Harbor, Buffalo, NY",
            price: "Free",
            featured: false,
            month: "Apr",
            day: "12"
        },
        {
            id: "pride-buffalo",
            name: "Pride Buffalo Festival",
            description: "A vibrant celebration of diversity and inclusion at the Buffalo waterfront.",
            image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=1200",
            category: "cultural community entertainment",
            badges: ["Cultural", "Community"],
            date: "June 15-17, 2026",
            time: "12:00 PM",
            location: "Canalside, Buffalo, NY",
            price: "$45",
            featured: false,
            month: "Jun",
            day: "15-17"
        },
        {
            id: "spiritual-workshop",
            name: "Spiritual Awakening Workshop",
            description: "Explore inner peace and mindfulness in this guided spiritual journey.",
            image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=1200",
            category: "faith spirituality wellness",
            badges: ["Spirituality", "Wellness"],
            date: "May 20, 2026",
            time: "10:00 AM",
            location: "North Park Theatre, Buffalo, NY",
            price: "$15",
            featured: false,
            month: "May",
            day: "20"
        },
        {
            id: "shakespeare-park",
            name: "Shakespeare in Delaware Park",
            description: "One of the largest free outdoor Shakespeare festivals in the country.",
            image: "https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?w=1200",
            category: "art cultural",
            badges: ["Art", "Theater", "Free"],
            date: "June 20 - Aug 20, 2026",
            time: "07:30 PM",
            location: "Delaware Park, Buffalo, NY",
            price: "Free",
            featured: false,
            month: "Jun",
            day: "20"
        },
        {
            id: "taste-of-buffalo",
            name: "Taste of Buffalo Celebration",
            description: "Celebrates many cuisines and cultures with restaurants, food trucks, and wineries.",
            image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=1200",
            category: "cultural food entertainment",
            badges: ["Food", "Desi"],
            date: "July 11-12, 2026",
            time: "11:00 AM",
            location: "Niagara Square, Downtown Buffalo, NY",
            url: "https://www.tasteofbuffalo.com",
            featured: true,
            month: "Jul",
            day: "11-12"
        }
    ],
    movies: [
        {
            id: "adventure-begins",
            name: "The Adventure Begins",
            description: "An epic journey of courage and discovery that will captivate audiences of all ages.",
            image: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800",
            category: "Action",
            rating: "PG-13",
            showtimes: ["2:30 PM", "5:15 PM", "8:00 PM"],
            status: "now_playing",
            url: "https://www.fandango.com"
        },
        {
            id: "winters-tale",
            name: "Winter's Tale",
            description: "A magical story set in a winter wonderland, exploring hope and transformation.",
            image: "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=800",
            releaseDate: "Feb 14, 2026",
            category: "Romance",
            status: "coming_soon"
        }
    ],
    attractions: [
        {
            id: "niagara-falls",
            name: "Niagara Falls",
            description: "Experience the breathtaking power and beauty of one of the world's most famous waterfalls.",
            fullDescription: "Niagara Falls is not just a waterfall; it's a testament to the raw power of nature. To truly experience its majesty, start your day with the Maid of the Mist boat tour, which takes you right into the heart of the Horseshoe Falls. Afterward, walk through the Cave of the Winds to feel the 'tropical storm' force of the Bridal Veil Falls.\n\nFor a more peaceful experience, explore the miles of hiking trails on Goat Island or enjoy a picnic overlooking the upper rapids. As the sun sets, stay for the nightly illumination where the falls are lit in a rainbow of colors, followed by spectacular fireworks displays during the summer months.",
            image: "assets/images/niagara-falls.avif",
            category: "parks family",
            badges: ["Natural Wonder", "Parks & Nature"],
            hours: "Open 24/7",
            price: "Free Admission",
            location: "Niagara Falls State Park, NY",
            url: "https://www.niagarafallsstatepark.com",
            featured: true
        },
        {
            id: "albright-knox",
            name: "Buffalo AKG Art Museum",
            description: "World-renowned collection of modern and contemporary art in a newly renovated architectural setting.",
            fullDescription: "The Buffalo AKG Art Museum (formerly Albright-Knox) is an architectural and cultural masterpiece. Following its historic expansion, the museum now features the stunning 'Common Sky' installation in the town square. Your visit should begin in the Gundlach Building, where massive skylights illuminate some of the most important modern works in the world.\n\nDon't miss the 1962 building's classic galleries, which house masterpieces by Picasso, Matisse, and Pollock. The museum is perfectly situated at the edge of Delaware Park, making it ideal for a combined day of high culture and nature strolls. Be sure to check their calendar for 'M&T First Fridays' when admission is free for the community.",
            image: "https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=800",
            category: "arts museums",
            badges: ["Art", "Museums"],
            hours: "Tue-Sun 10AM-5PM",
            price: "$15 Adults",
            location: "Delaware Park, Buffalo, NY",
            url: "https://buffaloakg.org",
            featured: true
        },
        {
            id: "science-museum",
            name: "Buffalo Museum of Science",
            description: "Interactive science studios and exhibits showcasing over 700,000 specimens and artifacts.",
            fullDescription: "The Buffalo Museum of Science offers an adventure through time and space for explorers of all ages. Each of its interactive 'Science Studios' centers on a specific theme, from 'Explore YOU' (health and biology) to 'Buffalo in Space.' Kids will love the Kellogg Observatory, which offers breathtaking views of the stars through a fully restored telescope during special evening events.\n\nTo make the most of your visit, plan to spend at least three hours exploring the various levels. The museum's historic building itself is a marvel, located in the MLK Jr. Park district. Check out the 'SciType' artifacts in the research wings for a glimpse into the museum's incredible 150-year history of collection and discovery.",
            image: "assets/images/museum-of-science.jpg",
            category: "museums family",
            badges: ["Museums", "Family Friendly"],
            hours: "Daily 10AM-4PM",
            price: "$23 Adults",
            location: "1020 Humboldt Pkwy, Buffalo, NY 14211",
            url: "https://www.sciencebuff.org",
            featured: true
        },
        {
            id: "delaware-park",
            name: "Delaware Park",
            description: "350-acre centerpiece of Buffalo's park system, designed by Olmsted & Vaux, featuring Hoyt Lake.",
            fullDescription: "Designed by the legendary Frederick Law Olmsted, Delaware Park is the crown jewel of Buffalo's park system. The best way to enjoy it is to start at Hoyt Lake, where you can rent a rowboat during the summer months for a romantic or family outing on the water. The surrounding trails are perfect for joggers, cyclists, and those looking for a leisurely dog walk.\n\nThe park also hosts 'Shakespeare in Delaware Park,' one of the largest free outdoor Shakespeare festivals in the country. During the winter, the hills become a favorite spot for sledding. Whether you're visiting the Rose Garden or just finding a quiet spot under a giant willow tree, Delaware Park offers a peaceful escape in the middle of the city.",
            image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800",
            category: "parks family",
            badges: ["Parks & Nature", "Family Friendly"],
            hours: "Dawn to Dusk",
            price: "Free",
            location: "Buffalo, NY 14214",
            url: "https://bfloparks.org/parks/delaware-park/",
            featured: true
        },
        {
            id: "martin-house",
            name: "Darwin D. Martin House",
            description: "Frank Lloyd Wright's masterpiece of Prairie-style architecture and a national historic landmark.",
            fullDescription: "The Darwin D. Martin House is considered one of the most important works of Frank Lloyd Wright's career. It represents the pinnacle of his Prairie House ideal, blurring the lines between indoor and outdoor spaces. A guided tour is essential to appreciate the intricate art glass windows, the 'open' interior spaces, and the way Wright integrated the main house with the pergola, conservatory, and carriage house.\n\nArchitecture enthusiasts will marvel at the long horizontal lines and the complex geometric relationships found throughout the site. The Greatbatch Pavilion, a modern visitor center, provides excellent historical context before you step into the past. Be sure to book your tours in advance, as they often sell out, especially during the peak fall foliage season.",
            image: "assets/images/flw.jpg",
            category: "historic arts",
            badges: ["Historic Sites", "Arts & Culture"],
            hours: "Tours 10AM-4PM",
            price: "$25 Tours",
            location: "125 Jewett Pkwy, Buffalo, NY 14214",
            url: "https://martinhouse.org"
        },
        {
            id: "buffalo-zoo",
            name: "Buffalo Zoo",
            description: "The third oldest zoo in the US, home to animals from around the world and educational programs.",
            fullDescription: "Located nestled within the historic Delaware Park, the Buffalo Zoo is one of the city's most beloved family destinations. Highlights include the 'Arctic Edge' exhibit, where you can see polar bears and arctic foxes, and the 'M&T Bank Rainforest Falls,' a breathtaking indoor lush tropical environment. \n\nFor a more interactive experience, don't miss the animal feedings and keeper talks scheduled throughout the day. The zoo's size makes it very walkable, even for little ones, and the historic buildings (like the Heritage Farm) offer a charming backdrop to your wild adventure. It's a year-round destination, but the animals are often most active during the crisp morning hours just after opening.",
            image: "https://images.unsplash.com/photo-1534567153574-2b12153a87f0?w=800",
            category: "family parks",
            badges: ["Family Friendly", "Parks & Nature"],
            hours: "Daily 10AM-4PM",
            price: "$22.50 Adults",
            location: "300 Parkside Ave, Buffalo, NY 14214",
            url: "https://buffalozoo.org"
        },
        {
            id: "sheas-buffalo",
            name: "Shea's Performing Arts Center",
            description: "Historic 1926 movie palace hosting Broadway tours, concerts, and premier live entertainment.",
            fullDescription: "Stepping into Shea's Buffalo Theatre is like traveling back to the Gilded Age. Built in 1926 and featuring stunning Neo-Spanish Baroque decor, it is one of the few Tiffany-designed theatres still in existence. To fully enjoy it, try to book tickets for a major Broadway touring production, but even a smaller concert or film screening allows you to admire the incredible crystal chandeliers and hand-carved details.\n\nThe theatre is located in the heart of Buffalo's Theatre District, surrounded by excellent dining options for a pre-show meal. If you're a fan of history, look for their special 'behind the scenes' tours which allow you to see the original Wurlitzer pipe organ—one of the largest in the world still in its original home.",
            image: "assets/images/sheas.jpg",
            category: "arts historic",
            badges: ["Arts & Culture", "Historic Sites"],
            hours: "Performance Times",
            price: "Varies",
            location: "646 Main St, Buffalo, NY 14202",
            url: "https://www.sheas.org"
        },
        {
            id: "canalside",
            name: "Canalside",
            description: "Buffalo's revitalized waterfront destination with year-round events, ice skating, and water activities.",
            fullDescription: "Canalside is the heart of Buffalo's waterfront renaissance. During the summer, it's the place to go for kayak rentals, bike ferries to Outer Harbor, and free concerts that draw thousands. You can explore the naval ships at the Buffalo & Erie County Naval & Military Park or just lounge in one of the many Adirondack chairs along the boardwalk.\n\nIn the winter, Canalside transforms into a wonderland with one of the largest outdoor skating rinks in the Northeast, complete with 'ice bikes' and curling lanes. It's a vibrant, constantly changing space that offers something new every week. Don't forget to grab a snack at one of the local food vendors while you enjoy the sunset over Lake Erie.",
            image: "assets/images/canalside.jpg",
            category: "family parks",
            badges: ["Family Friendly", "Parks & Nature"],
            hours: "Open 24/7",
            price: "Free Admission",
            location: "44 Prime St, Buffalo, NY 14202",
            url: "https://buffalowaterfront.com/canalside"
        }
    ],
    articles: [
        {
            id: "money-mindfulness",
            title: "30 Day Money and Mindfulness Challenge",
            description: "Transform your relationship with money through daily mindfulness practices.",
            image: "assets/images/article-mindfulness.jpg",
            badges: ["Wealth", "Challenge"],
            readTime: "5 min read",
            url: "https://yourbliss.us/post/30-day-money-and-mindfulness-challenge"
        },
        {
            id: "business-love",
            title: "Falling in Love with Your Business",
            description: "Learn why embracing your entrepreneurial journey is vital for both your service and your soul.",
            image: "assets/images/article-business-love.png",
            badges: ["Wealth", "Growth"],
            readTime: "6 min read",
            url: "https://yourbliss.us/post/falling-love-your-business"
        },
        {
            id: "modern-happiness",
            title: "Why Modern Happiness Isn't Just Romantic",
            description: "Exploring the multifaceted nature of fulfillment beyond traditional relationships.",
            image: "assets/images/article-happiness.png",
            badges: ["Happiness", "Wellness"],
            readTime: "8 min read",
            url: "https://yourbliss.us/post/why-modern-happiness-isnt-just-romantic"
        }
    ],
    recipes: [
        {
            id: "chocolate-lava-cake",
            title: "Chocolate Lava Cake",
            description: "A decadent and rich chocolate lava cake that is perfect for a special occasion.",
            image: "assets/images/choc-lava-cake.webp",
            badges: ["Dessert"],
            url: "https://yourbliss.us/post/chocolate-lava-cakes-two"
        },
        {
            id: "lentil-soup",
            title: "Vegan Lentil Soup",
            description: "A warming, protein-rich plant-based soup perfect for a healthy dinner.",
            image: "assets/images/lentil-soup.webp",
            badges: ["Dinner", "Vegan"],
            url: "https://yourbliss.us/post/lentil-soup"
        },
        {
            id: "stuffed-zucchini",
            title: "Stuffed Zucchini",
            description: "A refreshing, vibrant dish with bell peppers, mozzarella, and some fresh herbs.",
            image: "assets/images/stuffed-zuch.avif",
            badges: ["Lunch", "Healthy"],
            url: "https://yourbliss.us/post/stuffed-zucchini"
        }
    ],
    exploreBuffalo: [
        {
            id: "restaurants",
            icon: '<i class="fas fa-utensils" style="color: var(--color-primary);"></i>',
            title: "Restaurants & Dining",
            description: "Discover Buffalo's vibrant food scene, from cozy cafes to fine dining. Special highlights on featured restaurants unique vibes.",
            badges: ["200+ Restaurants", "Desi Cuisine"],
            link: "pages/restaurant2.html",
            btnText: "Explore Restaurants",
            btnClass: "btn-primary",
            featured: true
        },
        {
            id: "events",
            icon: '<i class="fas fa-calendar-alt" style="color: var(--color-primary);"></i>',
            title: "Events & Activities",
            description: "From cultural festivals to fitness classes, discover events happening around Buffalo. Special focus on Desi community events.",
            badges: ["This Weekend", "Cultural Events"],
            link: "pages/events.html",
            btnText: "Browse Events",
            btnClass: "btn-primary",
            featured: true
        },
        {
            id: "attractions",
            icon: '<i class="fas fa-landmark" style="color: var(--color-secondary);"></i>',
            title: "Attractions & Places",
            description: "Explore museums, parks, galleries, and historic sites. Plan your perfect Buffalo adventure with our curated guides.",
            badges: ["Museums", "Parks"],
            link: "pages/attractions.html",
            btnText: "Discover Places",
            btnClass: "btn-secondary",
            featured: true
        }
    ]
};
